"""迁移脚本

Revision ID: 030542a87dfa
Revises: 000000000001
Create Date: 2026-07-11 16:00:40.813990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '030542a87dfa'
down_revision: Union[str, None] = '000000000001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platform_menu', 'client')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platform_menu', sa.Column('client', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), server_default=sa.text("'pc'"), nullable=False, comment='终端(pc:管理端桌面 app:移动端)'))
    # ### end Alembic commands ###
