"""迁移脚本

Revision ID: 16d2aa16594e
Revises: 5fe8b5f855e5
Create Date: 2026-06-30 23:02:18.043809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16d2aa16594e'
down_revision: Union[str, None] = '5fe8b5f855e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == 'sqlite':
        with op.batch_alter_table('ai_evidence_file') as batch_op:
            batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True, comment='Owner user ID'))
            batch_op.create_index(batch_op.f('ix_ai_evidence_file_user_id'), ['user_id'], unique=False)
            batch_op.create_foreign_key(
                'fk_ai_evidence_file_user_id_sys_user',
                'sys_user',
                ['user_id'],
                ['id'],
                onupdate='CASCADE',
                ondelete='CASCADE',
            )
    else:
        op.add_column('ai_evidence_file', sa.Column('user_id', sa.Integer(), nullable=True, comment='Owner user ID'))
        op.create_index(op.f('ix_ai_evidence_file_user_id'), 'ai_evidence_file', ['user_id'], unique=False)
        op.create_foreign_key('fk_ai_evidence_file_user_id_sys_user', 'ai_evidence_file', 'sys_user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == 'sqlite':
        with op.batch_alter_table('ai_evidence_file') as batch_op:
            batch_op.drop_constraint('fk_ai_evidence_file_user_id_sys_user', type_='foreignkey')
            batch_op.drop_index(batch_op.f('ix_ai_evidence_file_user_id'))
            batch_op.drop_column('user_id')
    else:
        op.drop_constraint('fk_ai_evidence_file_user_id_sys_user', 'ai_evidence_file', type_='foreignkey')
        op.drop_index(op.f('ix_ai_evidence_file_user_id'), table_name='ai_evidence_file')
        op.drop_column('ai_evidence_file', 'user_id')
    # ### end Alembic commands ###
