"""迁移脚本

Revision ID: 5fe8b5f855e5
Revises: 
Create Date: 2026-06-30 15:25:41.090764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fe8b5f855e5'
down_revision: Union[str, None] = '000000000001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_user', sa.Column('monthly_salary', sa.Numeric(precision=10, scale=2), nullable=True, comment='月工资(元)'))
    op.add_column('sys_user', sa.Column('hire_date', sa.Date(), nullable=True, comment='入职日期'))
    op.add_column('sys_user', sa.Column('company_name', sa.String(length=128), nullable=True, comment='公司名称'))
    op.add_column('sys_user', sa.Column('position_name', sa.String(length=64), nullable=True, comment='岗位名称'))
    op.add_column('sys_user', sa.Column('contract_type', sa.String(length=32), nullable=True, comment='合同类型(劳动合同/劳务合同/无合同)'))
    op.add_column('sys_user', sa.Column('social_insurance', sa.Boolean(), nullable=True, comment='是否缴纳社保'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sys_user', 'social_insurance')
    op.drop_column('sys_user', 'contract_type')
    op.drop_column('sys_user', 'position_name')
    op.drop_column('sys_user', 'company_name')
    op.drop_column('sys_user', 'hire_date')
    op.drop_column('sys_user', 'monthly_salary')
    # ### end Alembic commands ###
